# Rebuilt from Gitakis08/chat21-ionic master @ 2c227b9f.
# Pinned to the pushed Docker Hub digest on 2026-05-25.
FROM dockerakis08/chat21-ionic:20260525-2c227b9f@sha256:2affa6c4e6da319b053e774810c091b9445578c4b585693b1bc7e54fb2279032

RUN sed -i "s#<title>.*</title>#<title>Zemark chat</title>#g" /usr/share/nginx/html/index.html
