# Local runtime wrapper layered on top of the committed design-studio source build.
FROM design-studio:local

RUN sed -i "s#<title>.*</title>#<title>Pobuca Converse</title>#g" /usr/share/nginx/html/index.html
